# Generated by Django 5.0.6 on 2024-06-28 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField()),
                ('site_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('whatsApp_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedIn_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('google_map_url', models.URLField(blank=True, null=True)),
                ('meta_og_title', models.TextField()),
                ('meta_og_description', models.TextField()),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
