# Generated by Django 5.0.6 on 2024-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_alter_sitesetting_apple_touch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='apple_touch',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/apple_touch.jpg'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/favicon.jpg'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/logo.jpg'),
        ),
    ]
