# Generated by Django 5.0.6 on 2024-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_sitesetting_apple_touch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='apple_touch',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/'),
        ),
    ]
